const questions = [
{"question":"Qu'est-ce que le CRUD?", "answer":"L'acronyme informatique anglais CRUD désigne les quatre opérations de base pour la persistance des données, en particulier le stockage d'informations en base de données. Soit : create : créer read : lire update : mettre à jour delete : supprimer."},
{"question":"Qu'est-ce que React", "answer":"React est une bibliothèque JavaScript open-source qui est utilisée pour construire des interfaces utilisateur spécifiquement pour des applications d'une seule page. Single page application, Créer des composants"},
{"question":"Qu'est ce qu'axios?", "answer":"Axios est une librairie cliente HTTP qui vous permet de faire des requêtes sur une route donnée. Il peut s'agir d'une API externe ou de votre propre serveur backend Node.js"},
{"question":"A quoi sert dotenv", "answer":" Le module dotenv Le dotenv est un module sans dépendance qui charge les variables d'environnement à partir d'un fichier . fichier env dans le processus. env.Dotenv vous permet de séparer les secrets de votre code source. Ceci est utile dans un environnement collaboratif (par exemple, travail ou open source) où vous ne souhaitez peut-être pas partager vos identifiants de connexion à la base de données avec d'autres personnes. Au lieu de cela, vous pouvez partager le code source tout en permettant à d'autres personnes de créer leur propre fichier ."},
{"question":"Qu'est ce qu'un JWT", "answer":"Les « JSON Web Token » ou JWT sont des jetons générés par un serveur lors de l’authentification d’un utilisateur sur une application Web, et qui sont ensuite transmis au client. Ils seront renvoyés avec chaque requête HTTP au serveur, ce qui lui permettra d’identifier l’utilisateur.Il est composé d’un header, payload et signature.Pour ce faire, les informations contenues dans le jeton sont signées à l’aide d’une clé privée détenue par le serveur. Quand il recevra à nouveau le jeton, le serveur n’aura qu’à comparer la signature envoyée par le client et celle qu’il aura générée avec sa propre clé privée et à comparer les résultats. Si les signatures sont identiques, le jeton est valide."},
  ];
  
  export default questions;
  